### ISSUE TITLE
Improve multi-file upload

### ISSUE THREAD

**Issue by chriseth** [ethereum/source-verify#10] opened 2019-12-18 15:40 UTC
The file upload mechanism should be done in client-side javascript to allow for the following:
 - select multiple files for upload
 - determine client-side which files are metadata files
 - try to discover the linked source files in the list
 - report which source files are missing
 - be able to work with multiple metadata files at the same time

Some of these tasks could also be done server-side, but the state should be kept on the client side.

It should still be possible to work with "dumb clients", i.e. external file uploads not using the client-side javascript, so some functionality should be put in modules that can be used both on the client and on the server side.

**Comment by chriseth** [comment] 2020-01-14 15:32
Parts of this item are split out into #29 #30

**Comment by marcgarreau** [comment] 2020-01-15 22:35
@chriseth I've got some time now to give to these issues. Been a while since I've written/compiled any solidity, though, so an assist would help me make better use of time. Things that would help:

- more description/logs from the error that is being seen with multiple file uploads
- sample files to upload - even better if they are valid, but reliably reproduce an issue
- requirements of a valid file

cc/ @cgewecke, in case you can lend a hand. 

In the meantime, will start to look for answers to these myself.

**Comment by cgewecke** [comment] 2020-01-16 02:45
@marcgarreau Not sure how far you got with this but I will be working on it a bit tomorrow.  

Will sketch out a spec suite and include some metadata and sources, including error cases.

**Comment by chriseth** [comment] 2020-01-16 10:02
I split up this issue and would propose to first work on this: https://github.com/ethereum/source-verify/issues/29

**Comment by edisinovcic** [comment] 2020-03-04 19:05
Should this issue be closed? @chriseth

**Comment by edisinovcic** [comment] 2020-03-09 16:49
Support multiple metadata files

**Comment by cgewecke** [comment] 2020-03-10 22:21
Opened #82 for the multiple metadata files, closing here.

**Closed by cgewecke** 2020-03-10 22:21 UTC
